In [1]:
# Import libraries 

import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel("C:/Users/HP/Desktop/End to End Project/Ecommerce_Unclean_Project.xlsx")

In [3]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [8]:
df.shape

(524, 15)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          502 non-null    float64
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  503 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 61.5+ KB

In [12]:
df.describe()

              Phone         Qty   Unit_Price
count  4.910000e+02  448.000000   462.000000
mean   9.543738e+09    2.794643  3176.272727
std    2.647419e+08    1.976997  2971.838671
min    9.104441e+09   -1.000000   499.000000
25%    9.313005e+09    1.000000   999.000000
50%    9.532206e+09    3.000000  1999.000000
75%    9.793310e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [6]:
df.isna().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(11)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [ ]:
# Replace ['N/A', "NULL", " "]   with  NaN

df.replace(['N/A', "NULL", " "], np.nan, inplace=True)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,NaN,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,NaN,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [21]:
# Remove Extra Spaces 

df = df.apply(lambda x : x.str.strip() if x.dtype == 'str' else x)

In [24]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'Email', 'Phone', 'City',
       'State', 'Product', 'Category', 'Qty', 'Unit_Price', 'Discount',
       'Payment_Mode', 'Order_Status', 'Delivery_Date'],
      dtype='str')

In [26]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2025

In [30]:
# Standardize Text Fromat 
# Convert Text into proper Case. 

df['Customer_Name'] = df['Customer_Name'].str.title()
df['City'] = df['City'].str.title()
df['State'] = df['State'].str.title()
df['Product'] = df['Product'].str.title()
df['Category'] = df['Category'].str.title()

In [31]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2025

In [38]:
# Valiate Email Id 
# Keep only valid email record.

df = df[df['Email'].str.contains('@', na=False)]

In [39]:
# Convert Date columns 

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')   # NAT
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'], errors='coerce')   # NAT

C:\Users\HP\AppData\Local\Temp\ipykernel_10040\3501975868.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')   # NAT

In [41]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'Email', 'Phone', 'City',
       'State', 'Product', 'Category', 'Qty', 'Unit_Price', 'Discount',
       'Payment_Mode', 'Order_Status', 'Delivery_Date'],
      dtype='str')

In [42]:
# Convert Numeric Columns 

cols = ['Qty', 'Unit_Price', 'Discount']

for i in cols: 
    df[i] = pd.to_numeric(df[i], errors='coerce')

In [44]:
# Remove Invalid Quantity 

df = df[df['Qty'] > 0 ]

In [47]:
# Fill Missing Values 

df['Discount'] = df['Discount'].fillna(0)
df['Phone'] = df['Phone'].fillna('Unknown')
df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

In [60]:
df[df['Order_ID'].isna()]

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
71,NaN,2025-01-26,Vikas,vikas17@gmail.com,9814518863.0,Mumbai,Maharashtra,Chair,Furniture,4.0,4999.0,15.0,NetBanking,Cancelled,2025-01-26
144,NaN,2025-01-15,Sneha,sneha17@gmail.com,9151754926.0,Lucknow,Up,Bottle,Home,5.0,4999.0,5.0,COD,Returned,2025-01-15
217,NaN,2025-01-26,Rahul,rahul38@gmail.com,9240228562.0,Mumbai,Maharashtra,Mouse,Electronics,5.0,499.0,10.0,UPI,Pending,2025-01-26
290,NaN,2025-06-24,Rahul,rahul60@gmail.com,9250231514.0,Pune,Maharashtra,Laptop,Electronics,2.0,1499.0,0.0,COD,Pending,2025-06-24
363,NaN,2025-06-23,Sneha,sneha38@gmail.com,9546087489.0,Pune,Maharashtra,Shoes,Fashion,5.0,9999.0,0.0,Wallet,Returned,2025-06-23
436,NaN,2025-01-14,Priya,priya40@gmail.com,9861729728.0,Delhi,Delhi,Bottle,Home,2.0,499.0,0.0,COD,Cancelled,2025-01-14

In [63]:
df.groupby('Product')['Unit_Price'].median()

Product
Bottle    1499.0
Chair     1999.0
Laptop    1999.0
Mouse     1999.0
Shoes     1999.0
Watch     2299.0
Name: Unit_Price, dtype: float64

In [65]:
df['Unit_Price'] = df['Unit_Price'].fillna(
    df.groupby('Product')['Unit_Price'].transform('median')
)

In [66]:
df.isna().sum()

Order_ID          6
Order_Date       47
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price        0
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date    32
dtype: int64

In [68]:
df[df['Delivery_Date'].isnull()][
    ['Order_ID', 'Order_Status', 'Order_Date']
]

    Order_ID Order_Status Order_Date
7    ORD1009      Pending        NaT
16   ORD1018    Delivered        NaT
38   ORD1040     Returned        NaT
43   ORD1045      Pending        NaT
52   ORD1054      Pending        NaT
78   ORD1080     Returned        NaT
97   ORD1099      Pending        NaT
115  ORD1117    Delivered        NaT
118  ORD1120    Cancelled        NaT
124  ORD1126      Pending        NaT
142  ORD1144     Returned        NaT
158  ORD1160    Delivered        NaT
198  ORD1200      Pending        NaT
205  ORD1207    Delivered        NaT
232  ORD1234    Delivered        NaT
238  ORD1240      Pending        NaT
241  ORD1243    Cancelled        NaT
278  ORD1280    Delivered        NaT
295  ORD1297      Pending        NaT
318  ORD1320    Cancelled        NaT
340  ORD1342    Delivered        NaT
349  ORD1351     Returned        NaT
358  ORD1360      Pending        NaT
367  ORD1369     Returned        NaT
376  ORD1378    Cancelled        NaT
385  ORD1387    Delivered        NaT
398  ORD1400     Returned        NaT
403  ORD1405     Returned        NaT
475  ORD1477    Delivered        NaT
478  ORD1480    Delivered        NaT
493  ORD1495     Returned        NaT
520  ORD1609      Pending        NaT

In [69]:
df[df['Delivery_Date'].isnull()]['Order_Status'].value_counts()

Order_Status
Pending      10
Delivered    10
Returned      8
Cancelled     4
Name: count, dtype: int64

In [70]:
df[
    df['Delivery_Date'].isnull() &
    (df['Order_Status'] == 'Delivered')
][['Order_ID', 'Order_Date', 'Order_Status']]

    Order_ID Order_Date Order_Status
16   ORD1018        NaT    Delivered
115  ORD1117        NaT    Delivered
158  ORD1160        NaT    Delivered
205  ORD1207        NaT    Delivered
232  ORD1234        NaT    Delivered
278  ORD1280        NaT    Delivered
340  ORD1342        NaT    Delivered
385  ORD1387        NaT    Delivered
475  ORD1477        NaT    Delivered
478  ORD1480        NaT    Delivered

In [71]:
df[df['Order_Date'].isnull()]['Order_Status'].value_counts()

Order_Status
Pending      15
Delivered    15
Returned     12
Cancelled     5
Name: count, dtype: int64

In [72]:
df[['Order_Date', 'Delivery_Date']].isnull().sum()

Order_Date       47
Delivery_Date    32
dtype: int64

In [73]:
df.groupby('Product')['Unit_Price'].agg(
    ['count', 'nunique', 'median']
)

         count  nunique  median
Product
Bottle      69        7  1499.0
Chair       60        7  1999.0
Laptop      66        7  1999.0
Mouse       65        7  1999.0
Shoes       64        7  1999.0
Watch       56        8  2299.0

In [74]:
df['Unit_Price'] = df['Unit_Price'].fillna(
    df.groupby('Product')['Unit_Price'].transform('median')
)

In [75]:
df['Unit_Price'].isnull().sum()

np.int64(0)

In [76]:
df[df['Order_ID'].isnull()]

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
71,NaN,2025-01-26,Vikas,vikas17@gmail.com,9814518863.0,Mumbai,Maharashtra,Chair,Furniture,4.0,4999.0,15.0,NetBanking,Cancelled,2025-01-26
144,NaN,2025-01-15,Sneha,sneha17@gmail.com,9151754926.0,Lucknow,Up,Bottle,Home,5.0,4999.0,5.0,COD,Returned,2025-01-15
217,NaN,2025-01-26,Rahul,rahul38@gmail.com,9240228562.0,Mumbai,Maharashtra,Mouse,Electronics,5.0,499.0,10.0,UPI,Pending,2025-01-26
290,NaN,2025-06-24,Rahul,rahul60@gmail.com,9250231514.0,Pune,Maharashtra,Laptop,Electronics,2.0,1499.0,0.0,COD,Pending,2025-06-24
363,NaN,2025-06-23,Sneha,sneha38@gmail.com,9546087489.0,Pune,Maharashtra,Shoes,Fashion,5.0,9999.0,0.0,Wallet,Returned,2025-06-23
436,NaN,2025-01-14,Priya,priya40@gmail.com,9861729728.0,Delhi,Delhi,Bottle,Home,2.0,499.0,0.0,COD,Cancelled,2025-01-14

In [77]:
df.isnull().sum()

Order_ID          6
Order_Date       47
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price        0
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date    32
dtype: int64

In [79]:
df.shape

(380, 15)

In [81]:
# Feature Engineering 

# Total Sales 


df['Sales'] = df['Qty'] * df['Unit_Price']

In [82]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02,24995.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05,5997.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10,1497.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0

In [83]:
# Net Amount 

df["Net_Amount"] = df["Sales"] - (df['Sales'] * df["Discount"] / 100)

In [84]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.00
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02,24995.0,19996.00
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05,5997.0,5697.15
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10,1497.0,1197.60
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00

In [85]:
# Profit (Ex = 20%)

df["Profit"] = df['Net_Amount'] * 0.20

In [86]:
df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.00,1599.20
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02,24995.0,19996.00,3999.20
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05,5997.0,5697.15,1139.43
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10,1497.0,1197.60,239.52
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20

In [87]:
# Order_Month

df["Order_Month"] = df['Order_Date'].dt.month_name()

In [89]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Order_Month
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.00,1599.20,June
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02,24995.0,19996.00,3999.20,February
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05,5997.0,5697.15,1139.43,May
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10,1497.0,1197.60,239.52,February
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20,February
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0,2998.00,599.60,NaN
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,1999.0,0.0,NetBanking,Delivered,2025-04-10,1999.0,1999.00,399.80,April
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0,2997.00,599.40,January
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-09-03,2997.0,2847.15,569.43,March

In [ ]:
# Order_Year

df["Order_Year"] = df['Order_Date'].dt.year

In [93]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Order_Month,Order_Year
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-03-07,7996.0,7996.00,1599.20,June,2025.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-09-02,24995.0,19996.00,3999.20,February,2025.0
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5.0,COD,Returned,2025-08-05,5997.0,5697.15,1139.43,May,2025.0
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,499.0,20.0,Wallet,Cancelled,2025-02-10,1497.0,1197.60,239.52,February,2025.0
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20,February,2025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,9999.0,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20,February,2025.0
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,0.0,Wallet,Pending,NaT,2998.0,2998.00,599.60,NaN,NaN
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,1999.0,0.0,NetBanking,Delivered,2025-04-10,1999.0,1999.00,399.80,April,2025.0
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,0.0,COD,Pending,2025-01-11,2997.0,2997.00,599.40,January,2025.0
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5.0,COD,Cancelled,2025-09-03,2997.0,2847.15,569.43,March,2025.0

In [96]:
df['Weekday'] = df['Order_Date'].dt.day_name()

In [97]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Order_Month,Order_Year,Weekday
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,2025-03-07,7996.0,7996.00,1599.20,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,2025-09-02,24995.0,19996.00,3999.20,February,2025.0,Monday
2,ORD1004,2025-05-06,Amit,amit6@gmail.com,9943310925.0,Jaipur,Rajasthan,Mouse,Electronics,3.0,...,5.0,COD,Returned,2025-08-05,5997.0,5697.15,1139.43,May,2025.0,Tuesday
5,ORD1007,2025-02-10,Rahul,rahul82@gmail.com,9517780193.0,Mumbai,Maharashtra,Mouse,Electronics,3.0,...,20.0,Wallet,Cancelled,2025-02-10,1497.0,1197.60,239.52,February,2025.0,Monday
6,ORD1008,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20,February,2025.0,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,2025-02-17,Rahul,rahul71@gmail.com,9789375429.0,Lucknow,Up,Mouse,Electronics,4.0,...,0.0,Card,Returned,2025-02-17,39996.0,39996.00,7999.20,February,2025.0,Monday
520,ORD1609,NaT,Rahul,rahul99@gmail.com,9552649559.0,Mumbai,Maharashtra,Bottle,Home,2.0,...,0.0,Wallet,Pending,NaT,2998.0,2998.00,599.60,NaN,NaN,NaN
521,ORD1610,2025-04-10,Rohit,rohit96@gmail.com,9700116928.0,Jaipur,Rajasthan,Mouse,Electronics,1.0,...,0.0,NetBanking,Delivered,2025-04-10,1999.0,1999.00,399.80,April,2025.0,Thursday
522,ORD1611,2025-01-11,Neha,neha22@gmail.com,9580304152.0,Jaipur,Rajasthan,Chair,Furniture,3.0,...,0.0,COD,Pending,2025-01-11,2997.0,2997.00,599.40,January,2025.0,Saturday
523,ORD1612,2025-03-03,Vikas,vikas46@gmail.com,9551158398.0,Jaipur,Rajasthan,Shoes,Fashion,3.0,...,5.0,COD,Cancelled,2025-09-03,2997.0,2847.15,569.43,March,2025.0,Monday

In [100]:
# Final data Validation 


df.info()

<class 'pandas.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       374 non-null    str
 1   Order_Date     333 non-null    datetime64[us]
 2   Customer_Name  380 non-null    str
 3   Email          380 non-null    str
 4   Phone          380 non-null    object
 5   City           380 non-null    str
 6   State          380 non-null    str
 7   Product        380 non-null    str
 8   Category       380 non-null    str
 9   Qty            380 non-null    float64
 10  Unit_Price     380 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    str
 13  Order_Status   380 non-null    str
 14  Delivery_Date  348 non-null    datetime64[us]
 15  Sales          380 non-null    float64
 16  Net_Amount     380 non-null    float64
 17  Profit         380 non-null    float64
 18  Order_Month    333 non-null    str
 19  Order_Year     333 non-null    float64
 20  Weekday        333 non-null    str
dtypes: datetime64[us](2), float64(7), object(1), str(11)
memory usage: 65.3+ KB

In [101]:

# Check missing values in every column
df.isnull().sum().sort_values(ascending=False)

Order_Date       47
Order_Month      47
Order_Year       47
Weekday          47
Delivery_Date    32
Order_ID          6
Phone             0
Customer_Name     0
Email             0
City              0
State             0
Product           0
Category          0
Payment_Mode      0
Discount          0
Unit_Price        0
Qty               0
Net_Amount        0
Sales             0
Order_Status      0
Profit            0
dtype: int64

In [103]:

# Count duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [104]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,Order_Year
count,333,380.000000,380.000000,380.000000,348,380.000000,380.000000,380.000000,333.0
mean,2025-04-02 17:35:08.108108,3.328947,3121.631579,7.802632,2025-05-01 04:12:24.827586,10642.197368,9823.222763,1964.644553,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,2025-01-02 00:00:00,499.000000,399.200000,79.840000,2025.0
25%,2025-02-14 00:00:00,2.000000,1499.000000,0.000000,2025-02-16 18:00:00,2997.000000,2586.112500,517.222500,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,5.000000,2025-04-19 00:00:00,5997.000000,5697.150000,1139.430000,2025.0
75%,2025-05-16 00:00:00,5.000000,4999.000000,15.000000,2025-06-18 00:00:00,12995.000000,11695.500000,2339.100000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,2025-12-06 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.458196,2903.135130,7.881075,NaN,11702.418236,11041.294556,2208.258911,0.0

In [105]:
# Export Data 

df.to_csv('Clean_Ecommerce.csv', index = False)

In [115]:

from sqlalchemy import create_engine
from sqlalchemy.engine import URL

connection_url = URL.create(
    "postgresql+psycopg2",
    username="postgres",
    password="Nikhil@123",
    host="localhost",
    port=5432,
    database="ecommerce"
)

engine = create_engine(connection_url)

# Test the connection
with engine.connect() as conn:
    print("PostgreSQL connected successfully!")

PostgreSQL connected successfully!

In [116]:

# Export DataFrame to PostgreSQL

df.to_sql(
    name="orders",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data successfully imported into PostgreSQL!")

Data successfully imported into PostgreSQL!